host: 0.0.0.0
port: 8080

postgres:
  database: some_db
  host: localhost
  maxsize: 5
  minsize: 1
  password: some_pass
  port: 5432
  user: some_usr
  url: some_url
  encrypion_key: some_key

shopify:
  auth_uri: https://{}.myshopify.com/admin/oauth/authorize?client_id={}&scope={}&redirect_uri={}&state={}&grant_options[]={}
  grant_options: per-user
  key: some_key
  redirect_uri: https://kuveedemo.herokuapp.com/auth/shopify/callback
  scope: write_orders,read_customers,read_content,write_content,read_products,write_products,read_themes,write_themes
  secret: some_scrt
  token_uri: https://{}.myshopify.com/admin/oauth/access_token
